name: Auto Deploy to cPanel

on:
  push:
    branches:
      - main # Ubah jadi 'master' kalau branch utama kamu namanya master

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 1. Ambil Kodingan Terbaru
      uses: actions/checkout@v4

    - name: 2. Siapkan Mesin PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Laravel 11 butuh PHP 8.2 ke atas

    - name: 3. Install Komponen Laravel
      run: composer install --optimize-autoloader --no-dev

    - name: 4. Siapkan Mesin Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: 5. Masak CSS & Tailwind (Vite)
      run: |
        npm install
        npm run build
        # Kloning folder build (Jurus andalan kita biar cPanel aman)
        cp -r public/build ./build

    - name: 6. Kirim ke cPanel via Kurir FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: / # Langsung dikirim ke public_html
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          .env*
          .htaccess
          index.php
          public/index.php
